Controllers/LoginsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgileRap_Process2.Data;
using AgileRap_Process2.Models;
using System.Text.Json;
using NuGet.Packaging;
using static System.Net.Mime.MediaTypeNames;
using Microsoft.AspNetCore.Http;
using BCrypt;

namespace AgileRap_Process2.Controllers
{
    public class LoginsController : BaseController
    {
        //AgileRap_Process2Context db = new AgileRap_Process2Context(); //dbContext
 
        // GET: LoginsController
        public ActionResult Login() //แสดงหน้า Login
        {

            if (HttpContext.Session.GetString("UserEmailSession") != null)
            {
                return RedirectToAction("Index", "Works");
            }
            User user = new User();
            return View(user);
        }

        // POST: LoginsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(User user) 
        {

            if (user.Email == null || user.Password == null) //กรณีกรอกข้อมูล Email และ Password ไม่ครบ
            {
                ViewBag.Message = "กรอกข้อมูลไม่ครบ!";
            }
            else //กรณีกรอกข้อมูล Email และ Password ไครบ
            {
                string hashedPassword = HashingHelper.HashPassword(user.Password); // HashPassword ที่กรอกเข้ามา

                User checkDB = db.User.Where(m => m.Email == user.Email && m.Password == hashedPassword).FirstOrDefault();//ตรวจหา Email และ Password ที่ตรงกัน

                //var checkDB = db.User.Where(m => m.Email == user.Email && m.Password == user.Password).FirstOrDefault();

                if (checkDB != null) //กรณีที่มีค่า(หมายความว่า Email และ Password ตรง)
                {
                    HttpContext.Session.SetString("UserEmailSession", checkDB.Email);
                    HttpContext.Session.SetString("UserNameSession", checkDB.Name);
                    HttpContext.Session.SetString("Default", "Operator");
                    HttpContext.Session.SetString("UserIDSession", checkDB.ID.ToString());
                    GlobalVariable.SetUserID(checkDB.ID);
                    TempData["AlertMessage"] = "ลงชื่อเข้าใช้สำเร็จ! ยินดีต้อนรับ  คุณ " + checkDB.Name;
                    return RedirectToAction("Index", "Works" , new { ProviderFilterValue = GlobalVariable.GetUserID().ToString()});
                }
                else //กรณีที่มีค่า(หมายความว่า Email และ Password ไม่ตรง)
                {
                    ViewBag.Message = "การเข้าสู่ระบบล้มเหลว ชื่อผู้ใช้หรือรหัสผ่านของคุณอาจไม่ถูกต้อง";
                }
            }
            return View(user);
        }

        public ActionResult Logout() //ฟังชันสำหรับออกจากระบบ
        {
            var tempSession = HttpContext.Session.GetString("UserEmailSession");

            if (tempSession != null) // ตรวจสอบค่า UserEmailSession
            {
                HttpContext.Session.Remove("UserEmailSession");
                HttpContext.Session.Remove("UserNameSession");
                HttpContext.Session.Remove("Default");
                HttpContext.Session.Remove("UserIDSession");
                GlobalVariable.ClearGlobalVariable();
                //HttpContext.Session.Clear();
                TempData["AlertMessage"] = "ออกจากระบบสำเร็จ!";
            }

            return View("Login");
        }

        public ActionResult Register() //สำหรับเข้าหน้าลงทะเบียน
        {
            User user = new User();
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(User user)
        {
            if (user.Email == null || user.Password == null || user.Name == null || user.ConfirmPassword == null)//กรณีกรอกข้อมูลไม่ครบ
            {
                ViewBag.InputWarning = "กรอกข้อมูลไม่ครบ! กรุณากรอกข้อมูลให้ครบ";
                return View(user);
            }

            var checkDB = db.User.Where(m => m.Email == user.Email).FirstOrDefault();

            if (checkDB != null) //กรณีตรวจหาอีเมลซํ้าได้
            {
                ViewBag.EmailWarning = "อีเมลนี้ลงทะเบียนแล้ว!";
                if (user.Password != user.ConfirmPassword) //กรณี Password และ ConfirmPassword ไม่ตรงกัน
                {
                    ViewBag.PasswordWarning = "รหัสผ่านกับยืนยันรหัสผ่านไม่ตรงกัน!";
                }
            }
            else //กรณีที่อีเมลไม่ซํ้า
            {
                if (user.Password != user.ConfirmPassword) //กรณี Password และ ConfirmPassword ไม่ตรงกัน
                {
                    ViewBag.PasswordWarning = "รหัสผ่านกับยืนยันรหัสผ่านไม่ตรงกัน!";
                }
                else //กรณี Password และ ConfirmPassword ตรงกัน
                {
                    //string hashedPassword = BCrypt.Net.BCrypt.HashPassword(user.Password);
                    //user.Password = hashedPassword;
                    //user.Password = HashingHelper.HashPassword(user.Password);
                    //user.IsDelete = false;
                    //user.CreateDate = DateTime.Now;
                    //user.UpdateDate = DateTime.Now;
                    //db.User.Add(user);
                    user.Insert(db);
                    db.SaveChanges();
                    TempData["AlertMessage"] = "ลงทะเบียนสำเร็จ!";
                    return RedirectToAction("Login");
                }
            }
            return View(user);
        }

        public ActionResult RegisterSuccess()
        {
            return View();
        }

    }
}

Views/Shared/_Footer.cshtml
<footer class="fixed-bottom">
    <div class="text-center p-3" style="background-image: linear-gradient(to bottom, rgba(255, 255, 255, 1), rgba(255, 255, 255, 0.90));">
        &copy; @DateTime.Now.Year - AgileRap_Process2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer> 

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgileRap_Process2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-multiselect.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/UniversalCss.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/TestTemplateNavbar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AgileRap_Process2.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/GlitchTextTest.css" asp-append-version="true" />
</head>
<body>
    <header class="fixed-top">
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AgileRap_Process2</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
        @Html.ActionLink("Works", "Index", "Works", new
        {
        RequseterFilter = Context.Session.GetString("RequseterFilter"),
        ProviderFilterValue = Context.Session.GetString("ProviderFilterValue"),
        ProjectFilter = Context.Session.GetString("ProjectFilter"),
        StatusFilter = Context.Session.GetString("StatusFilter"),
        IsChangePage = true

        }, new { @class = "nav-link text-dark" })
        </li>

        </ul>
        <ul class="navbar-nav flex-grow-0">
        @if (Context.Session.GetString("UserEmailSession") != null)
        {
        <li class="nav-item ">
        <a style="color:darkmagenta;" class="nav-link" disabled>@Context.Session.GetString("UserNameSession")</a>
        </li>

        <li class="nav-item ">
        <a style="color:darkcyan;" class="nav-link" disabled>@Context.Session.GetString("UserEmailSession")</a>
        </li>

        <li class="nav-item ">
        <a class="nav-link text-danger" asp-area="" asp-controller="Logins" asp-action="Logout">Logout</a>
        </li>
        }
        else
        {
        <li class="nav-item ">
        <a class="nav-link text-primary" asp-area="" asp-controller="Logins" asp-action="Login">Login</a>
        </li>
        }

        </ul>
        </div>
        </div>
        </nav> *@

        @* <nav>
        <ul>
        <li>
        <a asp-area="" asp-controller="Home" asp-action="Index">AgileRap_Process2</a>
        </li>
        <li>
        @Html.ActionLink("Works", "Index", "Works", new
        {
        RequseterFilter = Context.Session.GetString("RequseterFilter"),
        ProviderFilterValue = Context.Session.GetString("ProviderFilterValue"),
        ProjectFilter = Context.Session.GetString("ProjectFilter"),
        StatusFilter = Context.Session.GetString("StatusFilter"),
        IsChangePage = true

        })
        </li>

        </ul>
        <ul>
        @if (Context.Session.GetString("UserEmailSession") != null)
        {
        <li disabled>
        <a style="color:darkmagenta;" disabled>@Context.Session.GetString("UserNameSession")</a>
        </li>

        <li disabled>
        <a style="color:darkcyan;" disabled>@Context.Session.GetString("UserEmailSession")</a>
        </li>

        <li>
        <a style="color:red;" asp-area="" asp-controller="Logins" asp-action="Logout">Logout</a>
        </li>
        }
        else
        {
        <li>
        <a style="color:blue;" asp-area="" asp-controller="Logins" asp-action="Login">Login</a>
        </li>
        }

        </ul>
        </nav> *@

        <nav>
            <div class="logo"><a asp-area="" asp-controller="Home" asp-action="Index">AgileRap_Process2</a></div>
            <ul>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li>
                    @Html.ActionLink("Works", "Index", "Works", new
                        {
                            RequseterFilter = Context.Session.GetString("RequseterFilter"),
                            ProviderFilterValue = Context.Session.GetString("ProviderFilterValue"),
                            ProjectFilter = Context.Session.GetString("ProjectFilter"),
                            StatusFilter = Context.Session.GetString("StatusFilter"),
                            IsChangePage = true

                        })
                </li>
                @if (Context.Session.GetString("UserEmailSession") != null)
                {
                    <li class="profile-dropdown">
                        <a style="color:white;" disabled class="profile-button">Profile</a>
                        <div class="dropdown-content">
                            <a style="color:white;" disabled>@Context.Session.GetString("UserNameSession")</a>
                            <a style="color:white;" disabled>@Context.Session.GetString("UserEmailSession")</a>
                            <a style="color:red;" asp-area="" asp-controller="Logins" asp-action="Logout">Logout</a>
                        </div>
                    </li>
                }
                else
                {
                    <li>
                        <a style="color:blue;" asp-area="" asp-controller="Logins" asp-action="Login">Login</a>
                    </li>
                }

            </ul>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*     <footer class="border-top footer text-muted bg-white">
    <div class="container">
    &copy; 2024 - AgileRap_Process2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>   *@

    @await Html.PartialAsync("_Footer")
    @*     <footer class="fixed-bottom">
    <div class="text-center p-3 bg-white">
    &copy; @DateTime.Now.Year - AgileRap_Process2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer> *@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap-multiselect.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>